#!/usr/bin/env bash
# Fork status + upstream bug probes.
#
#   scripts/fork-status.sh            print a report, rewrite notes/fork-probe-report.md
#   scripts/fork-status.sh --update   also refresh the status block in FORK.md
#
# Answers, with a timestamp attached: how far is this fork from upstream, and is
# each logged bug/fix still fork-only or has upstream caught up? Probe definitions
# live in scripts/fork-probes.tsv. Exit status is always 0 unless the run itself
# could not happen, so a schedule on this never looks like a code failure.

set -uo pipefail
cd "$(dirname "$0")/.." || exit 1

UPSTREAM_REF=${UPSTREAM_REF:-upstream/main}
PROBES=scripts/fork-probes.tsv
REPORT=notes/fork-probe-report.md
STATE=notes/fork-probe-state.tsv
FORKMD=FORK.md
UPDATE=0
[ "${1:-}" = "--update" ] && UPDATE=1

git fetch upstream --quiet 2>/dev/null || echo "warning: git fetch upstream failed; using local $UPSTREAM_REF" >&2

if ! git rev-parse --verify --quiet "$UPSTREAM_REF" >/dev/null; then
	echo "error: $UPSTREAM_REF not found (configure the upstream remote / fetch it)" >&2
	exit 1
fi
[ -f "$PROBES" ] || { echo "error: missing $PROBES" >&2; exit 1; }

SHA=$(git rev-parse --short "$UPSTREAM_REF")
SHADATE=$(git log -1 --format=%ad --date=short "$UPSTREAM_REF")
SUBJ=$(git log -1 --format=%s "$UPSTREAM_REF")
NOW=$(date -u '+%Y-%m-%d %H:%M UTC')
TODAY=$(date -u '+%Y-%m-%d')
AHEAD=$(git rev-list --count "$UPSTREAM_REF"..main 2>/dev/null || echo '?')
BEHIND=$(git rev-list --count main.."$UPSTREAM_REF" 2>/dev/null || echo '?')
DIFFSTAT=$(git diff --shortstat "$UPSTREAM_REF"...main 2>/dev/null | sed 's/^ *//')

# Row = id | kind | status | detail. Statuses are stable strings: they are diffed
# against the previous run to decide whether anything needs a human.
rows=()
changes=()
while IFS=$'\t' read -r id kind path pattern note; do
	case "$id" in ''|'#'*) continue ;; esac
	kind=$(printf '%s' "$kind" | tr -d ' ')
	found=0
	if git show "$UPSTREAM_REF:$path" 2>/dev/null | grep -Fq -- "$pattern"; then
		found=1
	fi
	case "$kind" in
	fix)
		if [ "$found" = 1 ]; then
			status='MERGED-UPSTREAM'; detail='upstream has this fix: drop the local patch at the next sync'
		else
			status='FORK-ONLY'; detail='still our patch to carry'
		fi
		;;
	bug)
		if [ "$found" = 1 ]; then
			status='PRESENT-UPSTREAM'; detail='bug still upstream: worth an upstream issue'
		else
			status='GONE-UPSTREAM'; detail='upstream code no longer shows it'
		fi
		;;
	file)
		if [ "$found" = 1 ]; then
			status='IN-UPSTREAM'; detail='upstream now ships something at this path'
		else
			status='FORK-ONLY'; detail='fork-only file'
		fi
		;;
	feature)
		if [ "$found" = 1 ]; then
			status='ALSO-UPSTREAM'; detail='upstream has this feature too: our copy may now conflict'
		else
			status='FORK-ONLY'; detail='fork-only feature'
		fi
		;;
	*)
		status='UNKNOWN-KIND'; detail="probe kind '$kind' is wrong"
		;;
	esac
	rows+=("$(printf '%-6s %-8s %-16s %-52s %s' "$id" "$kind" "$status" "$path" "$note")")
	printf '%s\t%s\n' "$id" "$status" >>"$STATE.new"
done <"$PROBES"

# Change detection against the previous state file.
if [ -f "$STATE" ]; then
	while IFS=$'\t' read -r id prev; do
		[ -n "${id:-}" ] || continue
		now=$(grep -P "^$id\t" "$STATE.new" 2>/dev/null | cut -f2)
		if [ -n "$now" ] && [ "$now" != "$prev" ]; then
			changes+=("$id: $prev -> $now")
		fi
	done <"$STATE"
fi

{
	echo "# Fork probe report"
	echo
	echo "_Generated by \`scripts/fork-status.sh\` on $NOW._"
	echo
	echo "| | |"
	echo "| --- | --- |"
	echo "| Upstream base | \`open-webui/computer\` @ \`$SHA\` ($SHADATE) — \"$SUBJ\" |"
	echo "| Fork commits ahead | $AHEAD |"
	echo "| Upstream commits we lack | $BEHIND |"
	echo "| Diff vs upstream | $DIFFSTAT |"
	echo
	if [ ${#changes[@]} -gt 0 ]; then
		echo "## Changed since the previous run"
		echo
		for c in "${changes[@]}"; do echo "- $c"; done
		echo
	fi
	echo "## Probes"
	echo
	echo '```'
	printf '%s\n' "${rows[@]}"
	echo '```'
	echo
	echo "Legend: \`MERGED-UPSTREAM\` = upstream has our fix, delete the local patch."
	echo "\`PRESENT-UPSTREAM\` = the bug is still in upstream code, reportable."
	echo "\`GONE-UPSTREAM\` = upstream no longer shows it (fixed by them, or the code moved)."
	echo "Definitions: \`scripts/fork-probes.tsv\`. Ledger: \`BUGS.md\`."
} >"$REPORT"

mv "$STATE.new" "$STATE"
cat "$REPORT"

if [ "$UPDATE" = 1 ] && [ -f "$FORKMD" ]; then
	python3 - "$FORKMD" "$SHA" "$SHADATE" "$SUBJ" "$AHEAD" "$BEHIND" "$DIFFSTAT" "$TODAY" <<'PY'
import re, sys
md, sha, shadate, subj, ahead, behind, diffstat, today = sys.argv[1:9]
block = (
	"<!-- fork-status:begin -->\n"
	"_Refreshed automatically by `scripts/fork-status.sh --update`; do not hand-edit._\n\n"
	"| | |\n| --- | --- |\n"
	f"| Upstream base | `open-webui/computer` @ `{sha}` ({shadate}) — \"{subj}\" |\n"
	f"| Fork commits ahead | {ahead} |\n"
	f"| Upstream commits we lack | {behind} |\n"
	f"| Diff vs upstream | {diffstat} |\n"
	f"| Probes last run | {today} |\n"
	"<!-- fork-status:end -->\n"
)
text = open(md, encoding="utf-8").read()
new, n = re.subn(r"<!-- fork-status:begin -->.*?<!-- fork-status:end -->\n",
                 block, text, flags=re.S)
if n:
	if new != text:
		open(md, "w", encoding="utf-8").write(new)
		print("\nFORK.md status block updated.")
	else:
		print("\nFORK.md status block already current.")
else:
	print("\nwarning: no <!-- fork-status:begin --> block in FORK.md; left untouched.", file=sys.stderr)
PY
fi

if [ ${#changes[@]} -gt 0 ]; then
	echo
	echo "ACTION NEEDED: ${#changes[@]} probe state change(s):"
	printf '  - %s\n' "${changes[@]}"
elif [ "$BEHIND" != 0 ] && [ -n "$BEHIND" ]; then
	echo
	echo "NOTE: upstream has $BEHIND commit(s) we do not have yet."
fi
